// This file is auto generated by icy-table.
#ifndef TABLE_COMPILER_INDEX
#define TABLE_COMPILER_INDEX
#define array_element_size(array) sizeof(array[0])
#define array_count(array) (sizeof(array)/array_element_size(array))
#include "icydb.h"
#include <stdlib.h>
#endif


event_table * event_table_create(const char * optional_name){
  static const char * const column_names[] = {(char *)"timestamp"};
  static const char * const column_types[] = {"u64"};
  event_table * instance = calloc(sizeof(event_table), 1);
  instance->column_names = (char **)column_names;
  instance->column_types = (char **)column_types;
  
  icy_table_init((icy_table * )instance, optional_name, 1, (unsigned int[]){sizeof(u64)}, (char *[]){(char *)"timestamp"});
  
  return instance;
}

void event_table_insert(event_table * table, u64 * timestamp, size_t count){
  void * array[] = {(void* )timestamp};
  icy_table_inserts((icy_table *) table, array, count);
}

void event_table_set(event_table * table, u64 timestamp){
  void * array[] = {(void* )&timestamp};
  icy_table_inserts((icy_table *) table, array, 1);
}

void event_table_lookup(event_table * table, u64 * keys, size_t * out_indexes, size_t count){
  icy_table_finds((icy_table *) table, keys, out_indexes, count);
}

void event_table_remove(event_table * table, u64 * keys, size_t key_count){
  size_t indexes[key_count];
  size_t index = 0;
  size_t cnt = 0;
  while(0 < (cnt = icy_table_iter((icy_table *) table, keys, key_count, NULL, indexes, array_count(indexes), &index))){
    icy_table_remove_indexes((icy_table *) table, indexes, cnt);
    index = 0;
  }
}

void event_table_clear(event_table * table){
  icy_table_clear((icy_table *) table);
}

void event_table_unset(event_table * table, u64 key){
  event_table_remove(table, &key, 1);
}

bool event_table_try_get(event_table * table, u64 * timestamp){
  void * array[] = {(void* )timestamp};
  void * column_pointers[] = {(void *)table->timestamp};
  size_t __index = 0;
  icy_table_finds((icy_table *) table, array[0], &__index, 1);
  if(__index == 0) return false;
  unsigned int sizes[] = {sizeof(u64)};
  for(int i = 1; i < 1; i++){
    if(array[i] != NULL)
      memcpy(array[i], column_pointers[i] + __index * sizes[i], sizes[i]); 
  }
  return true;
}

void event_table_print(event_table * table){
  icy_table_print((icy_table *) table);
}

size_t event_table_iter(event_table * table, u64 * keys, size_t keycnt, u64 * optional_keys_out, size_t * indexes, size_t cnt, size_t * iterator){
  return icy_table_iter((icy_table *) table, keys, keycnt, optional_keys_out, indexes, cnt, iterator);

}
