// This file is auto generated by icy-table.
#include "icydb.h"
typedef struct _event_table{
  char ** column_names;
  char ** column_types;
  size_t count;
  const bool is_multi_table;
  const int column_count;
  int (*cmp) (const u64 * k1, const u64 * k2);
  const size_t sizes[1];

  u64 * timestamp;
  icy_mem * timestamp_area;
}event_table;

event_table * event_table_create(const char * optional_name);
void event_table_set(event_table * table, u64 timestamp);
void event_table_insert(event_table * table, u64 * timestamp, size_t count);
void event_table_lookup(event_table * table, u64 * keys, size_t * out_indexes, size_t count);
void event_table_remove(event_table * table, u64 * keys, size_t key_count);
void event_table_clear(event_table * table);
void event_table_unset(event_table * table, u64 key);
bool event_table_try_get(event_table * table, u64 * timestamp);
void event_table_print(event_table * table);
size_t event_table_iter(event_table * table, u64 * keys, size_t keycnt, u64 * optional_keys_out, size_t * indexes, size_t cnt, size_t * iterator);
