// This file is auto generated by icy-table.
#ifndef TABLE_COMPILER_INDEX
#define TABLE_COMPILER_INDEX
#define array_element_size(array) sizeof(array[0])
#define array_count(array) (sizeof(array)/array_element_size(array))
#include "icydb.h"
#include <stdlib.h>
#endif


particles * particles_create(const char * optional_name){
  static const char * const column_names[] = {(char *)"id", (char *)"pos", (char *)"dir", (char *)"size", (char *)"lifetime", (char *)"type"};
  static const char * const column_types[] = {"int", "vec2", "vec2", "f32", "f32", "particle_type"};
  particles * instance = calloc(sizeof(particles), 1);
  instance->column_names = (char **)column_names;
  instance->column_types = (char **)column_types;
  
  icy_table_init((icy_table * )instance, optional_name, 6, (unsigned int[]){sizeof(int), sizeof(vec2), sizeof(vec2), sizeof(f32), sizeof(f32), sizeof(particle_type)}, (char *[]){(char *)"id", (char *)"pos", (char *)"dir", (char *)"size", (char *)"lifetime", (char *)"type"});
  
  return instance;
}

void particles_insert(particles * table, int * id, vec2 * pos, vec2 * dir, f32 * size, f32 * lifetime, particle_type * type, size_t count){
  void * array[] = {(void* )id, (void* )pos, (void* )dir, (void* )size, (void* )lifetime, (void* )type};
  icy_table_inserts((icy_table *) table, array, count);
}

void particles_set(particles * table, int id, vec2 pos, vec2 dir, f32 size, f32 lifetime, particle_type type){
  void * array[] = {(void* )&id, (void* )&pos, (void* )&dir, (void* )&size, (void* )&lifetime, (void* )&type};
  icy_table_inserts((icy_table *) table, array, 1);
}

void particles_lookup(particles * table, int * keys, size_t * out_indexes, size_t count){
  icy_table_finds((icy_table *) table, keys, out_indexes, count);
}

void particles_remove(particles * table, int * keys, size_t key_count){
  size_t indexes[key_count];
  size_t index = 0;
  size_t cnt = 0;
  while(0 < (cnt = icy_table_iter((icy_table *) table, keys, key_count, NULL, indexes, array_count(indexes), &index))){
    icy_table_remove_indexes((icy_table *) table, indexes, cnt);
    index = 0;
  }
}

void particles_clear(particles * table){
  icy_table_clear((icy_table *) table);
}

void particles_unset(particles * table, int key){
  particles_remove(table, &key, 1);
}

bool particles_try_get(particles * table, int * id, vec2 * pos, vec2 * dir, f32 * size, f32 * lifetime, particle_type * type){
  void * array[] = {(void* )id, (void* )pos, (void* )dir, (void* )size, (void* )lifetime, (void* )type};
  void * column_pointers[] = {(void *)table->id, (void *)table->pos, (void *)table->dir, (void *)table->size, (void *)table->lifetime, (void *)table->type};
  size_t __index = 0;
  icy_table_finds((icy_table *) table, array[0], &__index, 1);
  if(__index == 0) return false;
  unsigned int sizes[] = {sizeof(int), sizeof(vec2), sizeof(vec2), sizeof(f32), sizeof(f32), sizeof(particle_type)};
  for(int i = 1; i < 6; i++){
    if(array[i] != NULL)
      memcpy(array[i], column_pointers[i] + __index * sizes[i], sizes[i]); 
  }
  return true;
}

void particles_print(particles * table){
  icy_table_print((icy_table *) table);
}

size_t particles_iter(particles * table, int * keys, size_t keycnt, int * optional_keys_out, size_t * indexes, size_t cnt, size_t * iterator){
  return icy_table_iter((icy_table *) table, keys, keycnt, optional_keys_out, indexes, cnt, iterator);

}
