// This file is auto generated by icy-table.
#ifndef TABLE_COMPILER_INDEX
#define TABLE_COMPILER_INDEX
#define array_element_size(array) sizeof(array[0])
#define array_count(array) (sizeof(array)/array_element_size(array))
#include "icydb.h"
#include <stdlib.h>
#endif


squares * squares_create(const char * optional_name){
  static const char * const column_names[] = {(char *)"id", (char *)"pos", (char *)"size", (char *)"type"};
  static const char * const column_types[] = {"square_id", "vec2", "vec2", "square_type"};
  squares * instance = calloc(sizeof(squares), 1);
  instance->column_names = (char **)column_names;
  instance->column_types = (char **)column_types;
  
  icy_table_init((icy_table * )instance, optional_name, 4, (unsigned int[]){sizeof(square_id), sizeof(vec2), sizeof(vec2), sizeof(square_type)}, (char *[]){(char *)"id", (char *)"pos", (char *)"size", (char *)"type"});
  
  return instance;
}

void squares_insert(squares * table, square_id * id, vec2 * pos, vec2 * size, square_type * type, size_t count){
  void * array[] = {(void* )id, (void* )pos, (void* )size, (void* )type};
  icy_table_inserts((icy_table *) table, array, count);
}

void squares_set(squares * table, square_id id, vec2 pos, vec2 size, square_type type){
  void * array[] = {(void* )&id, (void* )&pos, (void* )&size, (void* )&type};
  icy_table_inserts((icy_table *) table, array, 1);
}

void squares_lookup(squares * table, square_id * keys, size_t * out_indexes, size_t count){
  icy_table_finds((icy_table *) table, keys, out_indexes, count);
}

void squares_remove(squares * table, square_id * keys, size_t key_count){
  size_t indexes[key_count];
  size_t index = 0;
  size_t cnt = 0;
  while(0 < (cnt = icy_table_iter((icy_table *) table, keys, key_count, NULL, indexes, array_count(indexes), &index))){
    icy_table_remove_indexes((icy_table *) table, indexes, cnt);
    index = 0;
  }
}

void squares_clear(squares * table){
  icy_table_clear((icy_table *) table);
}

void squares_unset(squares * table, square_id key){
  squares_remove(table, &key, 1);
}

bool squares_try_get(squares * table, square_id * id, vec2 * pos, vec2 * size, square_type * type){
  void * array[] = {(void* )id, (void* )pos, (void* )size, (void* )type};
  void * column_pointers[] = {(void *)table->id, (void *)table->pos, (void *)table->size, (void *)table->type};
  size_t __index = 0;
  icy_table_finds((icy_table *) table, array[0], &__index, 1);
  if(__index == 0) return false;
  unsigned int sizes[] = {sizeof(square_id), sizeof(vec2), sizeof(vec2), sizeof(square_type)};
  for(int i = 1; i < 4; i++){
    if(array[i] != NULL)
      memcpy(array[i], column_pointers[i] + __index * sizes[i], sizes[i]); 
  }
  return true;
}

void squares_print(squares * table){
  icy_table_print((icy_table *) table);
}

size_t squares_iter(squares * table, square_id * keys, size_t keycnt, square_id * optional_keys_out, size_t * indexes, size_t cnt, size_t * iterator){
  return icy_table_iter((icy_table *) table, keys, keycnt, optional_keys_out, indexes, cnt, iterator);

}
